### ISSUE TITLE
error: failed to select a version for the requirement `stm32f4xx-hal = "^0.13.1"`

### ISSUE THREAD

**Issue by brandonros** [stm32-rs/stm32f4xx-hal#493]
I see 0.13.1 pushed here: https://crates.io/crates/stm32f4xx-hal

Cargo.toml

```toml
[package]
name = "stm_pwm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
# panic
panic-probe = { version = "0.3", features = ["print-rtt"] }
# logging
rtt-target = { version = "0.3", features = ["cortex-m"] }
# hal
stm32f4xx-hal = { version = "0.13.1", features = ["stm32f407"] }

```

```
Brandons-MacBook-Air:stm_pwm brandonros 2022-05-07 11:53:07 $ cargo run
    Updating crates.io index
error: failed to select a version for the requirement `stm32f4xx-hal = "^0.13.1"`
candidate versions found which didn't match: 0.13.0, 0.12.0, 0.11.1, ...
location searched: crates.io index
required by package `stm_pwm v0.1.0 (/Users/brandonros/Desktop/stm_pwm)`
```
